"""Parameter sweep for v3c-style trader, using Kevin's Python backtester
(prosperity4bt). Subprocess invocation with --no-out so nothing is written
to disk per run.

The sweep is 1-D: hold two parameters at v3c defaults, sweep the third.
That keeps total runtime short (~5 min) and is sufficient to identify
which parameter actually matters.

Run:
    /opt/homebrew/bin/python3.12 sweep.py
"""
import csv
import os
import re
import subprocess
import tempfile
from pathlib import Path

HERE = Path(__file__).parent
KEVIN_REPO = Path("/Users/nickzhu/Desktop/NYU/2026 Spring/IMC Prosperity/imc-prosperity-4-backtester-kevin")
PYTHON = "/opt/homebrew/bin/python3.12"


TRADER_TEMPLATE = '''"""Generated by sweep.py — K={K}, BASELINE_SIZE={BASELINE_SIZE}, MAX_TRADE_SIZE={MAX_TRADE_SIZE}"""
from datamodel import Order, OrderDepth, TradingState
from typing import Dict, List, Tuple


class Trader:
    SUFFIXES = ["XS", "S", "M", "L", "XL"]
    SYMS = [f"PEBBLES_{{s}}" for s in SUFFIXES]
    POS_LIMIT = 10
    BASKET_FAIR = 50_000.0
    K = {K}
    MAX_TRADE_SIZE = {MAX_TRADE_SIZE}
    BASELINE_SIZE = {BASELINE_SIZE}
    OFFSET = 1

    def run(self, state: TradingState) -> Tuple[Dict[str, List[Order]], int, str]:
        result: Dict[str, List[Order]] = {{}}
        books, mids = {{}}, {{}}
        for sym in self.SYMS:
            d = state.order_depths.get(sym)
            if d is None or not d.buy_orders or not d.sell_orders:
                return {{}}, 0, ""
            bb = max(d.buy_orders); ba = min(d.sell_orders)
            if bb >= ba:
                return {{}}, 0, ""
            books[sym] = (bb, ba)
            mids[sym] = (bb + ba) / 2.0
        basket_dev = sum(mids.values()) - self.BASKET_FAIR

        for sym in self.SYMS:
            bb, ba = books[sym]
            position = int(state.position.get(sym, 0))
            target = int(round(-self.K * basket_dev))
            target = max(-self.POS_LIMIT, min(self.POS_LIMIT, target))
            buy_room = self.POS_LIMIT - position
            sell_room = self.POS_LIMIT + position
            buy_signal_qty = max(0, target - position)
            sell_signal_qty = max(0, position - target)
            buy_qty = max(self.BASELINE_SIZE if buy_room > 0 else 0, buy_signal_qty)
            sell_qty = max(self.BASELINE_SIZE if sell_room > 0 else 0, sell_signal_qty)
            buy_qty = min(buy_qty, self.MAX_TRADE_SIZE, buy_room)
            sell_qty = min(sell_qty, self.MAX_TRADE_SIZE, sell_room)
            orders: List[Order] = []
            if buy_qty > 0:
                bid_price = bb + self.OFFSET
                if bid_price >= ba:
                    bid_price = ba - 1
                if bid_price > bb:
                    orders.append(Order(sym, bid_price, +buy_qty))
            if sell_qty > 0:
                ask_price = ba - self.OFFSET
                if ask_price <= bb:
                    ask_price = bb + 1
                if ask_price < ba:
                    orders.append(Order(sym, ask_price, -sell_qty))
            if orders:
                result[sym] = orders
        return result, 0, ""
'''


def run_one(K: float, baseline: int, max_size: int) -> tuple[float, int]:
    """Run Kevin BT in-process; return (pnl, trades=-1)."""
    with tempfile.TemporaryDirectory() as tmp:
        trader_path = Path(tmp) / "trader.py"
        trader_path.write_text(TRADER_TEMPLATE.format(
            K=K, BASELINE_SIZE=baseline, MAX_TRADE_SIZE=max_size))
        env = os.environ.copy()
        env["PYTHONPATH"] = str(KEVIN_REPO / "prosperity4bt")
        try:
            out = subprocess.run(
                [PYTHON, "-m", "prosperity4bt",
                 str(trader_path), "5",
                 "--no-vis", "--no-out", "--no-progress"],
                cwd=KEVIN_REPO, env=env,
                capture_output=True, text=True, check=True)
        except subprocess.CalledProcessError as e:
            print(f"  ! kevin BT failed (returncode={e.returncode})")
            print(f"  stderr tail:\n{e.stderr[-500:]}")
            return float("nan"), -1
        # Parse "Round 5 day X: <pnl>" lines + final "Total profit: <total>"
        m = re.search(r"^Total profit:\s+([\-\d,]+)\s*$", out.stdout, re.M)
        if not m:
            print(out.stdout[-1500:])
            raise RuntimeError("could not parse Total profit")
        # The script prints multiple "Total profit" lines (one per day + final).
        # Final = the last one.
        all_totals = re.findall(r"^Total profit:\s+([\-\d,]+)\s*$", out.stdout, re.M)
        pnl = float(all_totals[-1].replace(",", ""))
        return pnl, -1


def main():
    # 1-D sweeps: hold others at default, vary one
    DEFAULTS = {"K": 1.0, "baseline": 1, "max_size": 10}
    SWEEPS = [
        ("baseline", [0, 1, 2, 3, 5, 7, 9, 10]),
        ("K",        [0.25, 0.5, 1.0, 2.0, 4.0, 8.0]),
        ("max_size", [3, 5, 7, 10]),
    ]

    # Targeted combos for the K × baseline interaction (the K sweep was at
    # baseline=1; at baseline=5 the dynamics may differ).
    COMBOS = [
        # (K, baseline, max_size, "tag")
        (2.0,  5, 10, "combo"),   # original v3c was K=2, baseline=1
        (4.0,  5, 10, "combo"),
        (8.0,  5, 10, "combo"),
        (16.0, 5, 10, "combo"),
        (32.0, 5, 10, "combo"),
        (8.0,  3, 10, "combo"),
        (8.0,  7, 10, "combo"),
    ]

    out_csv = HERE / "sweep_results.csv"
    write_header = not out_csv.exists() or out_csv.stat().st_size == 0
    with out_csv.open("a", newline="") as f:
        w = csv.writer(f)
        if write_header:
            w.writerow(["sweep_dim", "K", "baseline", "max_size", "pnl"])
        for dim, values in SWEEPS:
            for v in values:
                params = dict(DEFAULTS)
                params[dim] = v
                pnl, _ = run_one(params["K"], params["baseline"], params["max_size"])
                w.writerow([dim, params["K"], params["baseline"], params["max_size"], pnl])
                f.flush()
                print(f"sweep={dim:<8}  K={params['K']:>5}  baseline={params['baseline']:>2}  max={params['max_size']:>2}  →  pnl={pnl:>9,.0f}")
        for K, b, m, tag in COMBOS:
            pnl, _ = run_one(K, b, m)
            w.writerow([tag, K, b, m, pnl])
            f.flush()
            print(f"sweep={tag:<8}  K={K:>5}  baseline={b:>2}  max={m:>2}  →  pnl={pnl:>9,.0f}")
    print(f"\nwrote {out_csv}")


if __name__ == "__main__":
    main()
