"""Sweep XL-asymmetric parameters on top of v4.

The data analysis (Round5/Analysis §4.5.3-4.5.4) showed XL is the absorber
leg: anti-correlated with each of XS/S/M/L at ~−0.50, with 2× the snap-event
noise of any other leg. Hypothesis: tightening XL's quoting (smaller size,
wider offset) reduces adverse selection without hurting spread capture on
the other 4 legs.

Sweep:
    XL_BASELINE ∈ {0, 1, 2, 3, 5}     (others fixed at 5)
    XL_OFFSET   ∈ {1, 2, 3}            (others fixed at 1)
    All 5 × 3 = 15 combos via Kevin BT.

Run:
    /opt/homebrew/bin/python3.12 sweep.py
"""
import csv
import os
import re
import subprocess
import tempfile
from pathlib import Path
from itertools import product

HERE = Path(__file__).parent
KEVIN_REPO = Path("/Users/nickzhu/Desktop/NYU/2026 Spring/IMC Prosperity/imc-prosperity-4-backtester-kevin")
PYTHON = "/opt/homebrew/bin/python3.12"


TRADER_TEMPLATE = '''"""Generated by sweep.py — XL_baseline={XL_BASELINE} XL_offset={XL_OFFSET}"""
from datamodel import Order, OrderDepth, TradingState
from typing import Dict, List, Tuple


class Trader:
    SUFFIXES = ["XS", "S", "M", "L", "XL"]
    SYMS = [f"PEBBLES_{{s}}" for s in SUFFIXES]
    POS_LIMIT = 10
    BASKET_FAIR = 50_000.0
    K = 1.0
    MAX_TRADE_SIZE = 10

    # Per-leg config: XS/S/M/L use the v4 optimum; XL is asymmetric.
    BASELINE = {{"XS": 5, "S": 5, "M": 5, "L": 5, "XL": {XL_BASELINE}}}
    OFFSET   = {{"XS": 1, "S": 1, "M": 1, "L": 1, "XL": {XL_OFFSET}}}

    def run(self, state: TradingState) -> Tuple[Dict[str, List[Order]], int, str]:
        result: Dict[str, List[Order]] = {{}}
        books, mids = {{}}, {{}}
        for sym in self.SYMS:
            d = state.order_depths.get(sym)
            if d is None or not d.buy_orders or not d.sell_orders:
                return {{}}, 0, ""
            bb = max(d.buy_orders); ba = min(d.sell_orders)
            if bb >= ba:
                return {{}}, 0, ""
            books[sym] = (bb, ba)
            mids[sym] = (bb + ba) / 2.0
        basket_dev = sum(mids.values()) - self.BASKET_FAIR

        for sym, suf in zip(self.SYMS, self.SUFFIXES):
            bb, ba = books[sym]
            position = int(state.position.get(sym, 0))
            baseline = self.BASELINE[suf]
            offset   = self.OFFSET[suf]

            target = int(round(-self.K * basket_dev))
            target = max(-self.POS_LIMIT, min(self.POS_LIMIT, target))
            buy_room = self.POS_LIMIT - position
            sell_room = self.POS_LIMIT + position
            buy_signal_qty = max(0, target - position)
            sell_signal_qty = max(0, position - target)
            buy_qty = max(baseline if buy_room > 0 else 0, buy_signal_qty)
            sell_qty = max(baseline if sell_room > 0 else 0, sell_signal_qty)
            buy_qty = min(buy_qty, self.MAX_TRADE_SIZE, buy_room)
            sell_qty = min(sell_qty, self.MAX_TRADE_SIZE, sell_room)
            orders: List[Order] = []
            if buy_qty > 0:
                bid_price = bb + offset
                if bid_price >= ba:
                    bid_price = ba - 1
                if bid_price > bb:
                    orders.append(Order(sym, bid_price, +buy_qty))
            if sell_qty > 0:
                ask_price = ba - offset
                if ask_price <= bb:
                    ask_price = bb + 1
                if ask_price < ba:
                    orders.append(Order(sym, ask_price, -sell_qty))
            if orders:
                result[sym] = orders
        return result, 0, ""
'''


def run_one(xl_baseline: int, xl_offset: int) -> float:
    with tempfile.TemporaryDirectory() as tmp:
        trader_path = Path(tmp) / "trader.py"
        trader_path.write_text(TRADER_TEMPLATE.format(
            XL_BASELINE=xl_baseline, XL_OFFSET=xl_offset))
        env = os.environ.copy()
        env["PYTHONPATH"] = str(KEVIN_REPO / "prosperity4bt")
        try:
            out = subprocess.run(
                [PYTHON, "-m", "prosperity4bt",
                 str(trader_path), "5",
                 "--no-vis", "--no-out", "--no-progress"],
                cwd=KEVIN_REPO, env=env,
                capture_output=True, text=True, check=True)
        except subprocess.CalledProcessError as e:
            print(f"  ! kevin BT failed: {e.returncode}")
            print(e.stderr[-400:])
            return float("nan")
        totals = re.findall(r"^Total profit:\s+([\-\d,]+)\s*$", out.stdout, re.M)
        if not totals:
            raise RuntimeError("no Total profit in stdout")
        return float(totals[-1].replace(",", ""))


def main():
    XL_BASELINE_VALUES = [0, 1, 2, 3, 5]
    XL_OFFSET_VALUES   = [1, 2, 3]

    out_csv = HERE / "sweep_results.csv"
    with out_csv.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["xl_baseline", "xl_offset", "pnl"])
        n = len(XL_BASELINE_VALUES) * len(XL_OFFSET_VALUES)
        i = 0
        for xl_b, xl_o in product(XL_BASELINE_VALUES, XL_OFFSET_VALUES):
            i += 1
            pnl = run_one(xl_b, xl_o)
            w.writerow([xl_b, xl_o, pnl])
            f.flush()
            print(f"[{i:>2}/{n}] XL_baseline={xl_b} XL_offset={xl_o}  →  pnl={pnl:>9,.0f}")
    print(f"\nwrote {out_csv}")


if __name__ == "__main__":
    main()
